### PR TITLE
Upgrade to Grafana 5.2.2

### PR DESCRIPTION
**Pull request by mbologna**
Version bump for Grafana

#### TODOs: 
- [x]  deploy grafana node and no regression found

### CODE REVIEW

**Comment by MalloZup** [comment]
@mbologna @moio  why is this in WIP? what is needed for this, outside of tests that the new version doesn't break?

**Comment by mbologna** [comment]
@MalloZup just tests are needed

**Comment by mbologna** [comment]
Tested and it seems everything is working.

screenshot from 2018-08-02 11-35-47

**Comment by moio** [comment]
Thanks, will take a look soon!

**Comment by moio** [comment]
Sorry for taking so long and thanks for this contribution!

**Pull request merged**
