### PR TITLE
grafana: use "sumaform" job in graphs

### PR DESCRIPTION
**Pull request by MalloZup**

### CODE REVIEW

**Comment by MalloZup** [comment]
ok

**Comment by MalloZup** [comment]
done

**Comment by moio** [comment]
This cannot work without a change in `prometheus.yml` as well.

Please always test PRs before removing the WIP tag! :angel:

**Comment by MalloZup** [comment]
@moio  yop right ! https://github.com/moio/sumaform/pull/286/commits/cd26db085d09e32d2cd4e82ef6552c1dd34e216a#diff-8189cc734700ed99e2e5985da8822b90L27

I test always before removing WIP, but in this case i tested on the grafana.mgr.suse.de the dashboard not the job, so was my fault on wrong test :+1:

**Pull request merged**
