### PR TITLE
move to sles15rc4

### PR DESCRIPTION
**Pull request by MalloZup**
- [x]  update obs libvirt img

- [x] update openstack obs img

- [ ] check obs build status of pkgs

- [ ] tests if ok locally

### CODE REVIEW

**Comment by moio** [comment]
Images are rebuilding at the moment because of https://github.com/moio/sumaform/issues/334#issuecomment-388771221

**Comment by moio** [comment]
Please merge this as soon as it is tested at least once on a client or minion (currently it cannot be tested as the image is blocked in the Build Service).

**Comment by MalloZup** [comment]
yop i will test asap obs finish to build i think it will be tomorrow the end of the build in obs

**Comment by Bischoff** [comment]
I'm already using it, and so far, so good.

**Comment by MalloZup** [comment]
thx

**Pull request merged**
