### PR TITLE
SLE12 SP1 is correct version for 3.1-released

### PR DESCRIPTION
**Pull request by Bischoff**
tested to work much better than SP2 ;-)

### CODE REVIEW

**Comment by mcalmer** [comment]
But it is not true. Initial when we released 3.1 we run it on top of SP2. 3.0 was released on top of SP1.

**Comment by Bischoff** [comment]
OK @mcalmer 

What triggered this PR is that package pattern-suma_proxy refuses to install on SP2 (failed dependancy):
```
# zypper in patterns-suma_proxy
(...)
Problem: nothing provides product(SLES) = 12.1 needed by product:SUSE-Manager-Proxy-3.0-0.x86_64
```

Uuuh, 3.0? After searching a bit, explanation is as following:
```
# zypper lr --url
(...)
5 | SUSE-Manager-Proxy-3.1-x86_64-Pool     | SUSE-Manager-Proxy-3.1-x86_64-Pool     | No      | ----      | No      | http://euklid.nue.suse.com/mirror/SuSE/build.suse.de/SUSE/Products/SUSE-Manager-Proxy/3.0/x86_64/product/
6 | SUSE-Manager-Proxy-3.1-x86_64-Update   | SUSE-Manager-Proxy-3.1-x86_64-Update   | No      | ----      | No      | http://euklid.nue.suse.com/mirror/SuSE/build.suse.de/SUSE/Updates/SUSE-Manager-Proxy/3.1/x86_64/update/  
```

See 3.1 pool with a 3.0 url :cat2: ... We are having a wrong repository. Closing this PR and creating an issue.

**Comment by Bischoff** [comment]
I have found the real error:
```
sumaform/salt/suse_manager_proxy/repos.d> grep 3.0/x86_64/product *
SUSE-Manager-Proxy-3.0-x86_64-Pool.repo:baseurl=http://{{ grains["mirror"] | default("euklid.nue.suse.com", true) }}/mirror/SuSE/build.suse.de/SUSE/Products/SUSE-Manager-Proxy/3.0/x86_64/product/
SUSE-Manager-Proxy-3.1-x86_64-Pool.repo:baseurl=http://{{ grains["mirror"] | default("euklid.nue.suse.com", true) }}/mirror/SuSE/build.suse.de/SUSE/Products/SUSE-Manager-Proxy/3.0/x86_64/product/
```

See the 3.1 proxy, it uses a 3.0 repo. I'll close this PR and create a new one.

**Comment by Bischoff** [comment]
https://github.com/moio/sumaform/pull/237 merged.

**Pull request closed without merging**
