### PR TITLE
[WIP] SLE 12 SP4 new default for 4.0 server and proxy

### PR DESCRIPTION
**Pull request by Bischoff**
(work in progress)

### CODE REVIEW

**Comment by juliogonzalez** [comment]
@Bischoff: 4.0 is to run on top of SLE15 SP4!!!!

SLE12 SP4 is for 3.1 and 3.2

**Comment by moio** [comment]
> @Bischoff: 4.0 is to run on top of SLE15 SP4!!!!

Well, not really, I bet you meant SLE 15 SP**1**

It would be great if that was enabled in this PR, although it is expected not to really work at this point in time.

**Comment by juliogonzalez** [comment]
Yeah, corrected now :-)

**Comment by Bischoff** [comment]
Thanks for the corrections, @juliogonzalez and @moio.

Are you sure about 3.1?

**Comment by juliogonzalez** [comment]
MU with support for SLE12SP4 as base OS was released last week :-)

**Pull request closed without merging**
