### PR TITLE
Remove client tools repos from srv after deployment

### PR DESCRIPTION
**Pull request by ktsamis**
Just 2 new modules in the standard repos.sls state in suse_manager_server that remove the client tools repositories. I deployed VM's with this state and no errors showed up, all the states were applied successfully, the repos were removed and the double ```zypper patch``` package conflict is not there.
Fixes issue #247

### CODE REVIEW

**Comment by ktsamis** [comment]
@moio  and @Bischoff for review whenever you have time :smile:

**Comment by Bischoff** [comment]
@ktsamis You have a "reviewers" button on the right ;-)

**Comment by ktsamis** [comment]
For SLE11 it is irrelevant because there is no server based on it. For SLE15 you are right, I did not see that it was there, I will add this as well today.

**Comment by ktsamis** [comment]
btw @Bischoff I can't edit reviewers or labels or anything, I don't have the right access to the repo.

**Comment by Bischoff** [comment]
Ah right, I had same problem in the old times.

**Comment by ktsamis** [comment]
@Bischoff SLE15 done, please note that it is not tested with a deployment because while we have sle15beta4 image, we don't have 3.2 suse manager yet

**Comment by Bischoff** [comment]
Now seems okay to me. We don't have feedback from Silvio yet, but I'll merge.

Thanks for this first PR @ktsamis ! :champagne:

**Comment by Bischoff** [comment]
It was breaking on head due to the problems with `yaml_jinja`.

The following code lets the installation succeed (but it does not remove the tools repositories) if `yaml_jinja` is broken:
```
{% if grains['osmajorrelease'] == '12' %}
remove_client_tools_pool:
  file.absent:
    - name: /etc/zypp/repos.d/SLE-Manager-Tools-SLE-12-x86_64-Pool.repo
{% elif grains['osmajorrelease'] == '15' %}
remove_client_tools_pool:
  file.absent:
    - name: /etc/zypp/repos.d/SLE-Manager-Tools-SLE-15-x86_64-Pool.repo
{% endif %}

{% if grains['osmajorrelease'] == '12' %}
remove_client_tools_update:
  file.absent:
    - name: /etc/zypp/repos.d/SLE-Manager-Tools-SLE-12-x86_64-Update.repo
{% elif grains['osmajorrelease'] == '15' %}
remove_client_tools_update:
  file.absent:
    - name: /etc/zypp/repos.d/SLE-Manager-Tools-SLE-15-x86_64-Update.repo
{% endif %}
```

**Pull request merged**
