### PR TITLE
WIP: set new database password

### PR DESCRIPTION
**Pull request by keichwa**
The SUMA Web UI does not accept dictionary-based passwords.

### CODE REVIEW

**Comment by MalloZup** [comment]
@keichwa  it is not so easy as it seems, to change this password, a bunch of programs rely on this `spacewalk` pwd

**Comment by moio** [comment]
OK @keichwa, that was not the only place in order to have the password correctly changed. I added a commit in this sense and I wonder now: would `susemanager` be an acceptable password?

I am asking because developers have to use this credential quite often, and I would like to use the easiest possible alternative by default.

**Comment by Bischoff** [comment]
To me, ```susemanager``` would be an acceptable password.

And yes, we need to fix it in many programs afterwards. But I don't think we can do anything about that, apart from doing it with care.

**Comment by keichwa** [comment]
Yes, susemanager would is an acceptable password.

While running /usr/lib/susemanager/bin/mgr-setup -m I see some 100 lines of this error prints (ugly, but in the end it seems to work):

ERROR:  role "spacewalk" does not exist
ERROR:  role "spacewalk" does not exist
ERROR:  role "spacewalk" does not exist

**Comment by MalloZup** [comment]
i would just vote for closing this

**Comment by Bischoff** [comment]
@keichwa ?

**Comment by moio** [comment]
Closing for the time being

**Pull request closed without merging**
