### PR TITLE
Add new repository for control-node

### PR DESCRIPTION
**Pull request by MalloZup**
this repository will contain only pkgs that are not rubygems

### CODE REVIEW

**Comment by MalloZup** [comment]
@moio  i think we should use `terraform init` instead of `terraform get` in the travis ci.

**Comment by MalloZup** [comment]
@moio i will test this tomorrow completely but you can review the salt part from my pov

**Comment by MalloZup** [comment]
@mcalmer @moio  feel free to review

**Comment by mcalmer** [comment]
@MalloZup wasn't there also a mirror file where you need to add new repositories to?

**Comment by MalloZup** [comment]
Afaik it was for sles only repod, but is a good point. I will take a look. Maybe for the controller we dont need it? Dunno lol

**Comment by MalloZup** [comment]
@mcalmer  i don't think mirror is relevant here.

@moio  can you confirm? thx

**Comment by MalloZup** [comment]
@mcalmer  ok thx fixed here : https://github.com/moio/sumaform/pull/241/files#diff-ab4f95bcf445605613ffabf8a28058d7R281

ready to review :rotating_light:

**Comment by moio** [comment]
@MalloZup please remember to rebase before merging next time, thanks!

**Comment by MalloZup** [comment]
@moio ok thx, and sorry for the unconvenience. usually i rebase always. 

buon natale

**Pull request merged**
