### PR TITLE
Sumaform Logos

### PR DESCRIPTION
**Pull request by area55git**

### CODE REVIEW

**Comment by MalloZup** [comment]
thx

**Comment by moio** [comment]
@area55git I am very deeply sorry to report that something went wrong while amending your PR. Anyway, I have merged manually your amended commit into master, and now your logo is on the README front page!

Great job and thanks for your patience. I was just too busy in the last few days and had no time for sumaform.

Now I know who to ask next time I need a better logo!

Thanks!

**Comment by area55git** [comment]
Pleased to contribute to your project, I am completely at your service.

**Comment by MalloZup** [comment]
@area55git  if you have time, look at this https://github.com/MalloZup/kubeojo/issues/2 , i am looking for a logo for a new starting project. 

If you want to contribute feel free, ciao

**Comment by area55git** [comment]
I think it's great, I'm going to send a proposal.

**Pull request closed without merging**
