### PR TITLE
[WIP] use new updated ruby repo for the testsuite

### PR DESCRIPTION
**Pull request by mcalmer**
Cleanup of an unused repo and put the currently used rpms inside: https://github.com/SUSE/spacewalk/issues/1549

Started to update some packages to new versions: https://github.com/SUSE/spacewalk/issues/1548

Running job to see what breaks: https://ci.nue.suse.com/view/Manager/view/Manager-Head/job/manager-Head-sumaform-cucumber/1902/

### CODE REVIEW

**Comment by mcalmer** [comment]
The run resulted in 28 errors. Needs investigation.

**Comment by moio** [comment]
@mcalmer any plans to continue activity on this?

**Comment by MalloZup** [comment]
@moio imho i am thinking why we couldn't use for rubygems a Gemfile with fixed version?
Imhot this could spare the need of creating all this rpms, and from experience, obs is always failing in rubygem because the change macros, so having a `Gemfile` is universal and more stable. (with fixed version)

What do you think?

**Comment by moio** [comment]
@MalloZup I am fine with that, only downside is that the testsuite is a bit more dependent on the presence of an Internet connection (it is already the case now).

I will accept a PR in this direction.

**Comment by moio** [comment]
@mcalmer are there any plans to continue on this or should I close it for now?

**Comment by mcalmer** [comment]
I do not like that the repo we currently use has "test" in the name. I think we should keep it open and try again.

**Comment by MalloZup** [comment]
@moio @mcalmer since now we use a Gemfile, we have less more dependencies on rpms.

I tackle this soon, and fix this issue

**Comment by MalloZup** [comment]
we can close this pr @mcalmer @moio since i will fix it in the next PR

**Comment by mcalmer** [comment]
Aggreed - closing

**Pull request closed without merging**
