### PR TITLE
[Depends on PR#387] Two more changes for terraform v11

### PR DESCRIPTION
**Pull request by Bischoff**
Transition from `version` to `product_version` in a line that is not covered by Dario's PR (#387).

### CODE REVIEW

**Comment by mbologna** [comment]
Since you're targeting dmaiocchi's PR https://github.com/moio/sumaform/pull/387 I think it's better either to rebase this on top of his branch or to clearly state that this PR is depending on that (so it cannot be merged by accident on master)

**Comment by Bischoff** [comment]
In any case, this is not working. I'll simplify it, and this will go on top of his branch as you recommand.

**Comment by Bischoff** [comment]
Simplified...

**Comment by MalloZup** [comment]
i pushed this commit directly on my branch!
https://github.com/moio/sumaform/pull/387/commits/065fcd9f06e53cc6fb337fecd007433cd3b7ede4

thx!

**Pull request closed without merging**
