### PR TITLE
Testsuite: do not install unneeded packages

### PR DESCRIPTION
**Pull request by MalloZup**
Fix this:
An error was encountered while installing package(s): Zypper command
failure: Package 'aaa_base-extras' not found.

### CODE REVIEW

**Comment by moio** [comment]
Where does that error come from exactly?

**Comment by moio** [comment]
Please share the full log. It is not clear from your description if this is a sumaform bug, a Salt bug or a testsuite bug.

**Comment by MalloZup** [comment]
@moio here https://ci.suse.de/user/manager/my-views/view/cucumber-manager/job/manager-3.1-reference-host/123/consoleFull

**Comment by MalloZup** [comment]
there is also this 'openscap-extra-probes' that is only avaible for sles12 clients.

**Comment by mcalmer** [comment]
I don't know anything about the extra-probes package. "openscap-utils" is required, but not extra-probes.
Maybe somebody just added all packages with "openscap" in the name?

**Comment by MalloZup** [comment]
i will test soon without this pkg to see if we need this or not

**Comment by moio** [comment]
Current patch LGTM, thanks @MalloZup.

Just remove the WIP and ping me anytime to merge

**Comment by MalloZup** [comment]
@moio ok thx, ok for me to merge.

**Pull request merged**
