### PR TITLE
update main.tf with sles12sp2

### PR DESCRIPTION
**Pull request by MalloZup**
improve the support to sles-12-sp2

### CODE REVIEW

**Comment by MalloZup** [comment]
i branched already the RPM, and did the build locally and in my home for sles-12-sp2.
obs.suse. seems pretty straight forward to build images.

Question, why in sp1 we had sles-12 repos? 

I think that in the kiwi we should have only sles-12-sp2 repo. what do you think?

**Comment by moio** [comment]
> Question, why in sp1 we had sles-12 repos?
> I think that in the kiwi we should have only sles-12-sp2 repo. what do you think?

I guess you refer to `<repository>` tags in the Kiwi files here.

Those actually refer to BS projects rather than distributed repos - we need them all as packages in the repos distributed to customers might come from earlier versions.

**Comment by MalloZup** [comment]
@moio ok thx. :)

**Comment by moio** [comment]
Reopened, this is still relevant!

**Pull request merged**
