### PR TITLE
Move controller to opensuse_leap423

### PR DESCRIPTION
**Pull request by MalloZup**
- [x]  remove SDK from mirror and other repos

- [x] everything deploy ok

- [x] No regression on tests

- [x] tests on openstack and libvirt OK

- [x] update production if neeeded

### CODE REVIEW

**Comment by MalloZup** [comment]
@moio a part from the run i scheduled  now, i think i considered everything, also the mirror part (feel free to cmment out if i missed something).

If the run works as prod with sles12sp3, i will update the production before merging this

**Comment by MalloZup** [comment]
for RPM: https://build.suse.de/project/show/Devel:Galaxy:cucumber-testsuite we build already for leap42.3

**Comment by moio** [comment]
In that case please adapt URLs in the .repo and minima.yml files

**Comment by MalloZup** [comment]
@moio ok thx  for the nitpick, updated it :+1:

**Comment by MalloZup** [comment]
production is ready

**Comment by MalloZup** [comment]
production is ready

**Pull request merged**
