### PR TITLE
Test: run Travis in containers instead of VMs

### PR DESCRIPTION
**Pull request by moio**
See https://docs.travis-ci.com/user/reference/trusty/#Routing-to-Trusty

### CODE REVIEW

**Comment by MalloZup** [comment]
@moio  we need sudo,  why sudo false, let the sudo be true !!! :)

**Comment by moio** [comment]
@MalloZup: look ma', no `sudo`!

**Comment by MalloZup** [comment]
@moio  where do you reload cached grains? 
are we sure that when removing the grains local and putting a new, we will have not the old data?

This was the reason for restarting the salt service ( i spoked with @meaksh  about that)

**Comment by moio** [comment]
If you use `salt-call` you do not need `salt-master` nor `salt-minion`, it is just one only self-contained execution.

The salt-minion package does not configure any custom grain, all custom grains are set by the script, so I see no reason to reload them.

**Comment by MalloZup** [comment]
ok for me then

merge this also then! :)
https://github.com/moio/sumaform/pull/176

**Pull request merged**
