### PR TITLE
Disable apt-daily.timer in Ubuntu minions for testsuite

### PR DESCRIPTION
**Pull request by mbologna**
To be tested.

### CODE REVIEW

**Comment by Bischoff** [comment]
Test running.

**Comment by Bischoff** [comment]
Tested, does not work:
```
root@ebi5-ubuntu:~# systemctl status apt-daily-upgrade.timer
* apt-daily-upgrade.timer - Daily apt upgrade and clean activities
   Loaded: loaded (/lib/systemd/system/apt-daily-upgrade.timer; enabled; vendor preset: enabled)
   Active: active (waiting) since Mon 2019-03-25 14:24:10 CET; 14min ago
  Trigger: Tue 2019-03-26 06:44:49 CET; 16h left

Mar 25 14:24:10 linux systemd[1]: Started Daily apt upgrade and clean activities.
```
It looks like the name of the timer is wrong :-( . I might have copied and pasted it from a forum without checking it was the same as the one I typed on my workstation.

**Comment by Bischoff** [comment]
It does not work because the new states are called much after the error happens.

**Comment by Bischoff** [comment]
@moio @mbologna I'll revert this one too. We'll work on a private branch until we have something more solid.

Sorry for the "inquinamento"...

**Comment by mcalmer** [comment]
What about disabling this already in the image ?

**Pull request merged**
